=begin comment

sts

This is the API for metamodel database

The version of the OpenAPI document: 1.0.0
Contact: mark.benson@nih.gov
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ValuesetApi');

my $api = WWW::OpenAPIClient::ValuesetApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ValuesetApi');

#
# get_list_of_value_sets test
#
{
    my $result = $api->get_list_of_value_sets();
}

#
# get_value_set_by_id test
#
{
    my $valueset_id = undef; # replace NULL with a proper value
    my $result = $api->get_value_set_by_id(valueset_id => $valueset_id);
}


1;
