# coding: utf-8

"""
    sts

    This is the API for metamodel database  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mark.benson@nih.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.term_api import TermApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTermApi(unittest.TestCase):
    """TermApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.term_api.TermApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_list_of_terms(self):
        """Test case for get_list_of_terms

        List all terms  # noqa: E501
        """
        pass

    def test_get_termy_by_id(self):
        """Test case for get_termy_by_id

        Get a property using ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
