# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ValueSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, url=None):  # noqa: E501
        """ValueSet - a model defined in OpenAPI

        :param id: The id of this ValueSet.  # noqa: E501
        :type id: str
        :param url: The url of this ValueSet.  # noqa: E501
        :type url: str
        """
        self.openapi_types = {
            'id': str,
            'url': str
        }

        self.attribute_map = {
            'id': 'id',
            'url': 'url'
        }

        self._id = id
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'ValueSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValueSet of this ValueSet.  # noqa: E501
        :rtype: ValueSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ValueSet.


        :return: The id of this ValueSet.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ValueSet.


        :param id: The id of this ValueSet.
        :type id: str
        """

        self._id = id

    @property
    def url(self):
        """Gets the url of this ValueSet.


        :return: The url of this ValueSet.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ValueSet.


        :param url: The url of this ValueSet.
        :type url: str
        """

        self._url = url
