# coding: utf-8

"""
    sts

    This is the API for metamodel database  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: mark.benson@nih.gov
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Term(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'value': 'str',
        'origin_definition': 'str',
        'origin_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'value': 'value',
        'origin_definition': 'origin_definition',
        'origin_id': 'origin_id'
    }

    def __init__(self, id=None, value=None, origin_definition=None, origin_id=None, local_vars_configuration=None):  # noqa: E501
        """Term - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._value = None
        self._origin_definition = None
        self._origin_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if value is not None:
            self.value = value
        if origin_definition is not None:
            self.origin_definition = origin_definition
        if origin_id is not None:
            self.origin_id = origin_id

    @property
    def id(self):
        """Gets the id of this Term.  # noqa: E501


        :return: The id of this Term.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Term.


        :param id: The id of this Term.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def value(self):
        """Gets the value of this Term.  # noqa: E501


        :return: The value of this Term.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Term.


        :param value: The value of this Term.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def origin_definition(self):
        """Gets the origin_definition of this Term.  # noqa: E501


        :return: The origin_definition of this Term.  # noqa: E501
        :rtype: str
        """
        return self._origin_definition

    @origin_definition.setter
    def origin_definition(self, origin_definition):
        """Sets the origin_definition of this Term.


        :param origin_definition: The origin_definition of this Term.  # noqa: E501
        :type: str
        """

        self._origin_definition = origin_definition

    @property
    def origin_id(self):
        """Gets the origin_id of this Term.  # noqa: E501


        :return: The origin_id of this Term.  # noqa: E501
        :rtype: str
        """
        return self._origin_id

    @origin_id.setter
    def origin_id(self, origin_id):
        """Sets the origin_id of this Term.


        :param origin_id: The origin_id of this Term.  # noqa: E501
        :type: str
        """

        self._origin_id = origin_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Term):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Term):
            return True

        return self.to_dict() != other.to_dict()
