=begin comment

sts

This is the API for metamodel database

The version of the OpenAPI document: 1.0.0
Contact: mark.benson@nih.gov
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::DefaultApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_node_by_id
#
# Find node by ID
# 
# @param int $node_id ID of node to return (required)
{
    my $params = {
    'node_id' => {
        data_type => 'int',
        description => 'ID of node to return',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_node_by_id' } = { 
        summary => 'Find node by ID',
        params => $params,
        returns => 'Node',
        };
}
# @return Node
#
sub get_node_by_id {
    my ($self, %args) = @_;

    # verify the required parameter 'node_id' is set
    unless (exists $args{'node_id'}) {
      croak("Missing the required parameter 'node_id' when calling get_node_by_id");
    }

    # parse inputs
    my $_resource_path = '/nodes/{nodeId}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'node_id'}) {
        my $_base_variable = "{" . "nodeId" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'node_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Node', $response);
    return $_response_object;
}

1;
