=begin comment

sts

This is the API for metamodel database

The version of the OpenAPI document: 1.0.0
Contact: mark.benson@nih.gov
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::NodeApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_list_of_nodes
#
# List all nodes 
# 
# @param string $model_id limit to nodes belonging to this model  (optional)
{
    my $params = {
    'model_id' => {
        data_type => 'string',
        description => 'limit to nodes belonging to this model ',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_list_of_nodes' } = { 
        summary => 'List all nodes ',
        params => $params,
        returns => 'Node',
        };
}
# @return Node
#
sub get_list_of_nodes {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/nodes';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'text/plain');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'model_id'}) {
        $query_params->{'modelId'} = $self->{api_client}->to_query_value($args{'model_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Node', $response);
    return $_response_object;
}

1;
